### PR TITLE
Fix mux port `uninitialized`

### LINKED ISSUE #307: Mux port `uninitialized` after restarting `linkmgrd`
## Issue Description:
After restarting `linkmgrd`, the mux ports are `uninitialized`:
```
 show mux status
PORT         STATUS    SERVER_STATUS    HEALTH         HWSTATUS    LAST_SWITCHOVER_TIME
-----------  --------  ---------------  -------------  ----------  ---------------------------
Ethernet0    active    active           uninitialized  consistent  2025-Aug-20 04:58:53.173587
Ethernet8    active    active           uninitialized  consistent  2025-Aug-20 04:58:53.290898
Ethernet16   active    active           uninitialized  consistent  2025-Aug-20 04:58:50.044327
Ethernet24   active    active           uninitialized  consistent  2025-Aug-20 04:58:50.044812
Ethernet32   active    active           uninitialized  consistent  2025-Aug-20 04:58:50.045315
Ethernet40   active    active           uninitialized  consistent  2025-Aug-20 04:58:50.033376
Ethernet64   active    active           uninitialized  consistent  2025-Aug-20 04:58:50.045144
Ethernet72   active    active           uninitialized  consistent  2025-Aug-20 04:58:50.032814
Ethernet80   active    active           uninitialized  consistent  2025-Aug-20 04:58:50.045969
Ethernet88   active    active           uninitialized  consistent  2025-Aug-20 04:58:50.046467
Ethernet96   active    active           uninitialized  consistent  2025-Aug-20 04:58:50.044154
Ethernet104  active    active           uninitialized  consistent  2025-Aug-20 04:58:50.046301
Ethernet112  active    active           uninitialized  consistent  2025-Aug-20 04:58:50.045807
Ethernet120  active    active           uninitialized  consistent  2025-Aug-20 04:58:53.116933
Ethernet128  active    active           uninitialized  consistent  2025-Aug-20 04:58:53.232121
Ethernet136  active    active           uninitialized  consistent  2025-Aug-20 04:58:50.061666
Ethernet144  active    active           uninitialized  consistent  2025-Aug-20 04:58:50.046132
Ethernet152  active    active           uninitialized  consistent  2025-Aug-20 04:58:50.045641
Ethernet176  active    active           uninitialized  consistent  2025-Aug-20 04:58:50.044637
Ethernet184  active    active           uninitialized  consistent  2025-Aug-20 04:58:50.044980
Ethernet192  active    active           uninitialized  consistent  2025-Aug-20 04:58:50.032987
Ethernet200  active    active           uninitialized  consistent  2025-Aug-20 04:58:50.033199
Ethernet208  active    active           uninitialized  consistent  2025-Aug-20 04:58:50.045477
Ethernet216  active    active           uninitialized  consistent  2025-Aug-20 04:58:50.046631
```

## how to reproduce
* run the following script

```
#!/bin/bash

set -x

while true; do
    echo "restarting linkmgrd"
    docker exec mux supervisorctl restart linkmgrd
    for i in {1..5}; do
        echo "Loop $i to check mux status"
        show mux status | grep uninitialized
        if [ $? -eq 0 ]; then
            echo "Mux is uninitialized"
            exit
        fi
        show mux status | grep unhealthy
        if [ $? -eq 1 ]; then
            echo "Mux is healthy"
            break
        fi
        echo ""
        sleep 2
    done
done
```

## syslog
```
2025 Aug 20 04:58:58.761429 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: MuxManager.cpp:247 updatePortCableType: Ethernet216: Port cable type: active-active
2025 Aug 20 04:58:58.765601 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: DbInterface.cpp:852 processProberType: Ethernet216: Link Prober type = {software}
2025 Aug 20 04:58:58.768057 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: MuxManager.cpp:187 addOrUpdateMuxPort: Ethernet216: server IP: 192.168.0.48
2025 Aug 20 04:58:58.768747 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: link_prober/LinkProberBase.cpp:718 generateGuid: Link Prober generated GUID: {0x0ae3957a}
2025 Aug 20 04:58:58.768880 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: link_prober/LinkProberBase.cpp:718 generateGuid: Link Prober generated GUID: {0x7ff5de9f}
2025 Aug 20 04:58:58.769233 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: link_prober/LinkProberBase.cpp:718 generateGuid: Link Prober generated GUID: {0xfc18cde9}
2025 Aug 20 04:58:58.769258 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: link_prober/LinkProberBase.cpp:718 generateGuid: Link Prober generated GUID: {0xc2ee7ad4}
2025 Aug 20 04:58:58.769310 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: link_prober/LinkProberBase.cpp:718 generateGuid: Link Prober generated GUID: {0x9f23dad8}
2025 Aug 20 04:58:58.769427 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: link_prober/LinkProberBase.cpp:718 generateGuid: Link Prober generated GUID: {0x65967ee3}
2025 Aug 20 04:58:58.769509 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: link_prober/LinkProberBase.cpp:718 generateGuid: Link Prober generated GUID: {0x3420af7f}
2025 Aug 20 04:58:58.769563 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: link_prober/LinkProberBase.cpp:718 generateGuid: Link Prober generated GUID: {0x74b466d0}
2025 Aug 20 04:58:58.769674 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: link_prober/LinkProberBase.cpp:718 generateGuid: Link Prober generated GUID: {0x3672cea5}
2025 Aug 20 04:58:58.769755 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: link_prober/LinkProberBase.cpp:718 generateGuid: Link Prober generated GUID: {0xe1f9cde6}
2025 Aug 20 04:58:58.769895 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: link_prober/LinkProberBase.cpp:718 generateGuid: Link Prober generated GUID: {0xb86d35ed}
2025 Aug 20 04:58:58.769967 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: link_prober/LinkProberBase.cpp:718 generateGuid: Link Prober generated GUID: {0xc807afcc}
2025 Aug 20 04:58:58.770075 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: link_prober/LinkProberBase.cpp:718 generateGuid: Link Prober generated GUID: {0x08d84f67}
2025 Aug 20 04:58:58.770297 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: MuxManager.cpp:210 addOrUpdateMuxPortSoCAddress: Ethernet216: SoC IP: 192.168.0.49
2025 Aug 20 04:58:58.770606 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: link_prober/LinkProberBase.cpp:718 generateGuid: Link Prober generated GUID: {0x61b4382c}
2025 Aug 20 04:58:58.770673 str3-7260cx3-acs-1 INFO mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:126 handleSwssSoCIpv4AddressUpdate: Ethernet216: detected Prober type HW(false)
2025 Aug 20 04:58:58.790087 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: MuxPort.cpp:481 handleTsaEnable: Ethernet216: configuring mux mode due to CONFIG DB tsa_enable notification: 0
2025 Aug 20 04:58:58.796068 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: MuxManager.cpp:232 updateMuxPortConfig: Ethernet216: Mux port config: auto
2025 Aug 20 04:58:58.830344 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: MuxManager.cpp:323 addOrUpdateMuxPortLinkState: Ethernet216: link state: up
2025 Aug 20 04:58:58.844796 str3-7260cx3-acs-1 INFO mux#linkmgrd: MuxManager.cpp:414 processProbeMuxState: Ethernet216: app db mux state: active
2025 Aug 20 04:58:58.844959 str3-7260cx3-acs-1 INFO mux#linkmgrd: MuxManager.cpp:429 processPeerMuxState: Ethernet216: state db peer mux state: active
2025 Aug 20 04:58:58.847481 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: MuxManager.cpp:349 addOrUpdateMuxPortMuxState: Ethernet216: state db mux state: active
2025 Aug 20 04:58:58.857994 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: MuxPort.cpp:413 handleDefaultRouteState: port: Ethernet216, state db default route state: ok
2025 Aug 20 04:58:58.874351 str3-7260cx3-acs-1 NOTICE mux#linkmgrd: MuxPort.cpp:413 handleDefaultRouteState: port: Ethernet216, state db default route state: ok
2025 Aug 20 04:58:58.889744 str3-7260cx3-acs-1 INFO mux#linkmgrd: MuxManager.cpp:429 processPeerMuxState: Ethernet216: state db peer mux state: active
```

## gdb trace

```
(gdb) thread apply all bt

Thread 5 (Thread 0x7fdd260d96c0 (LWP 3025) "linkmgrd"):
#0  0x00007fdd2a51cee6 in epoll_wait () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fdd2abf7c98 in swss::Select::poll_descriptors (this=this@entry=0x7fdd260d6fa0, c=c@entry=0x7fdd260d6d00, timeout=timeout@entry=1000, interrupt_on_signal=interrupt_on_signal@entry=false) at common/select.cpp:99
#2  0x00007fdd2abf7ea6 in swss::Select::select (this=this@entry=0x7fdd260d6fa0, c=c@entry=0x7fdd260d6d00, timeout=timeout@entry=1000, interrupt_on_signal=interrupt_on_signal@entry=false) at common/select.cpp:182
#3  0x000055924c00290e in mux::DbInterface::handleSwssNotification (this=0x55928932a1d0) at src/DbInterface.cpp:1845
#4  0x00007fdd2aafcb17 in ?? () from /lib/x86_64-linux-gnu/libboost_thread.so.1.74.0
#5  0x00007fdd2a49d1f5 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007fdd2a51cb00 in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 4 (Thread 0x7fdd268da6c0 (LWP 3024) "linkmgrd"):
#0  0x00007fdd2a56ed23 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x000055924c0134be in std::char_traits<char>::compare (__n=<optimized out>, __s2=<optimized out>, __s1=<optimized out>) at /usr/include/c++/12/bits/char_traits.h:385
#2  std::operator==<char> (__rhs=..., __lhs="0xcb73f822") at /usr/include/c++/12/bits/basic_string.h:3587
#3  std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::operator() (__y=..., __x="0xcb73f822", this=<optimized out>) at /usr/include/c++/12/bits/stl_function.h:378
#4  std::__detail::_Hashtable_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__detail::_Identity, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Hashtable_traits<true, true, true> >::_M_key_equals (__n=..., __k="0xcb73f822", this=<optimized out>) at /usr/include/c++/12/bits/hashtable_policy.h:1688
#5  std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Identity, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [clone .constprop.0] (__k="0xcb73f822", this=<optimized out>) at /usr/include/c++/12/bits/hashtable.h:1648
#6  0x000055924bf7fd38 in std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::find (__x="0xcb73f822", this=0x55924c05de20 <link_prober::LinkProberBase::mGuidSet[abi:cxx11]>) at /usr/include/c++/12/bits/unordered_set.h:650
#7  link_prober::LinkProberBase::generateGuid[abi:cxx11]() (this=this@entry=0x7fdd1c019ab0) at src/link_prober/LinkProberBase.cpp:715
#8  0x000055924bf80927 in link_prober::LinkProberBase::LinkProberBase (this=<optimized out>, muxPortConfig=..., ioService=..., linkProberStateMachinePtr=<optimized out>, this=<optimized out>, muxPortConfig=..., ioService=..., linkProberStateMachinePtr=<optimized out>) at src/link_prober/LinkProberBase.cpp:66
#9  0x000055924bfc6b28 in link_prober::LinkProberSw::LinkProberSw (linkProberStateMachinePtr=0x7fdd20066210, ioService=..., muxPortConfig=..., this=0x7fdd1c019ab0) at src/link_prober/LinkProberSw.cpp:45
#10 std::_Construct<link_prober::LinkProberSw, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__p=0x7fdd1c019ab0) at /usr/include/c++/12/bits/stl_construct.h:119
#11 std::allocator_traits<std::allocator<void> >::construct<link_prober::LinkProberSw, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__p=0x7fdd1c019ab0) at /usr/include/c++/12/bits/alloc_traits.h:635
#12 std::_Sp_counted_ptr_inplace<link_prober::LinkProberSw, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__a=..., this=0x7fdd1c019aa0) at /usr/include/c++/12/bits/shared_ptr_base.h:604
#13 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<link_prober::LinkProberSw, std::allocator<void>, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__a=..., __p=<optimized out>, this=<optimized out>) at /usr/include/c++/12/bits/shared_ptr_base.h:971
#14 std::__shared_ptr<link_prober::LinkProberSw, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<void>, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__tag=..., this=<optimized out>, this=<optimized out>, __tag=...) at /usr/include/c++/12/bits/shared_ptr_base.h:1712
#15 std::shared_ptr<link_prober::LinkProberSw>::shared_ptr<std::allocator<void>, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__tag=..., this=<optimized out>, this=<optimized out>, __tag=...) at /usr/include/c++/12/bits/shared_ptr.h:464
#16 std::make_shared<link_prober::LinkProberSw, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> () at /usr/include/c++/12/bits/shared_ptr.h:1010
#17 link_manager::ActiveActiveStateMachine::handleSwssSoCIpv4AddressUpdate (this=0x7fdd200653a0, address=...) at src/link_manager/LinkManagerStateMachineActiveActive.cpp:138
#18 0x000055924c0053bb in boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>::operator() (this=0x7fdd268d9960, a1=..., p=0x7fdd200653a0) at /usr/include/boost/bind/mem_fn_template.hpp:165
#19 boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> >::operator()<boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list0> (a=<synthetic pointer>..., f=..., this=0x7fdd268d9970) at /usr/include/boost/bind/bind.hpp:319
#20 boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > >::operator() (this=0x7fdd268d9960) at /usr/include/boost/bind/bind.hpp:1294
#21 boost::asio::asio_handler_invoke<boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > > > (function=...) at /usr/include/boost/asio/handler_invoke_hook.hpp:88
#22 boost_asio_handler_invoke_helpers::invoke<boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > >, boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > > > (context=..., function=...) at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:54
#23 boost::asio::detail::handler_work<boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > >, boost::asio::io_context::basic_executor_type<std::allocator<void>, 0u>, void>::complete<boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > > > (handler=..., function=..., this=<synthetic pointer>) at /usr/include/boost/asio/detail/handler_work.hpp:425
#24 boost::asio::detail::completion_handler<boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > >, boost::asio::io_context::basic_executor_type<std::allocator<void>, 0u> >::do_complete (owner=0x55928932d170, base=0x7fdd20049d40) at /usr/include/boost/asio/detail/completion_handler.hpp:74
#25 0x000055924bf78be5 in boost::asio::detail::scheduler_operation::complete (bytes_transferred=<optimized out>, ec=..., owner=<optimized out>, this=<optimized out>, this=<optimized out>, owner=<optimized out>, ec=..., bytes_transferred=<optimized out>) at /usr/include/boost/asio/detail/scheduler_operation.hpp:40
#26 boost::asio::detail::strand_service::do_complete (owner=0x55928932d170, base=0x7fdd20064a00, ec=...) at /usr/include/boost/asio/detail/impl/strand_service.ipp:169
#27 0x000055924c019db6 in boost::asio::detail::scheduler_operation::complete (bytes_transferred=<optimized out>, ec=..., owner=<optimized out>, this=<optimized out>, this=<optimized out>, owner=<optimized out>, ec=..., bytes_transferred=<optimized out>) at /usr/include/boost/asio/detail/scheduler_operation.hpp:40
#28 boost::asio::detail::scheduler::do_run_one (ec=..., this_thread=..., lock=..., this=0x55928932d170) at /usr/include/boost/asio/detail/impl/scheduler.ipp:481
#29 boost::asio::detail::scheduler::run(boost::system::error_code&) [clone .constprop.0] (this=0x55928932d170, ec=...) at /usr/include/boost/asio/detail/impl/scheduler.ipp:204
#30 0x000055924bffe3dc in boost::asio::io_context::run (this=<optimized out>) at /usr/include/boost/asio/impl/io_context.ipp:63
#31 0x00007fdd2aafcb17 in ?? () from /lib/x86_64-linux-gnu/libboost_thread.so.1.74.0
#32 0x00007fdd2a49d1f5 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#33 0x00007fdd2a51cb00 in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 3 (Thread 0x7fdd270db6c0 (LWP 3023) "linkmgrd"):
#0  std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Identity, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::_M_rehash_aux (this=<optimized out>, __bkt_count=29) at /usr/include/c++/12/bits/hashtable.h:2571
#1  std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Identity, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::_M_rehash (this=<optimized out>, __state=<optimized out>, __bkt_count=29) at /usr/include/c++/12/bits/hashtable.h:2541
#2  std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Identity, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::_M_insert_unique_node (this=<optimized out>, __n_elt=1, __node=0x7fdd180198f0, __code=16110033974232631699, __bkt=<optimized out>) at /usr/include/c++/12/bits/hashtable.h:2155
--Type <RET> for more, q to quit, c to continue without paging--
#3  std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Identity, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::_M_insert_unique<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, true> > > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, true> > > const&) [clone .constprop.0] (__k="0x9b91d3a0", __node_gen=..., __v=..., this=<optimized out>) at /usr/include/c++/12/bits/hashtable.h:2254
#4  0x000055924bf7ffca in std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Identity, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::_M_insert<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, true> > > > (__node_gen=..., __arg="0x9b91d3a0", this=0x55924c05de20 <link_prober::LinkProberBase::mGuidSet[abi:cxx11]>) at /usr/include/c++/12/bits/hashtable.h:903
#5  std::__detail::_Insert_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Identity, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::insert (__v="0x9b91d3a0", this=0x55924c05de20 <link_prober::LinkProberBase::mGuidSet[abi:cxx11]>) at /usr/include/c++/12/bits/hashtable_policy.h:893
#6  std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::insert (__x="0x9b91d3a0", this=0x55924c05de20 <link_prober::LinkProberBase::mGuidSet[abi:cxx11]>) at /usr/include/c++/12/bits/unordered_set.h:422
#7  link_prober::LinkProberBase::generateGuid[abi:cxx11]() (this=this@entry=0x7fdd18022e50) at src/link_prober/LinkProberBase.cpp:717
#8  0x000055924bf80927 in link_prober::LinkProberBase::LinkProberBase (this=<optimized out>, muxPortConfig=..., ioService=..., linkProberStateMachinePtr=<optimized out>, this=<optimized out>, muxPortConfig=..., ioService=..., linkProberStateMachinePtr=<optimized out>) at src/link_prober/LinkProberBase.cpp:66
#9  0x000055924bfc6b28 in link_prober::LinkProberSw::LinkProberSw (linkProberStateMachinePtr=0x7fdd20061290, ioService=..., muxPortConfig=..., this=0x7fdd18022e50) at src/link_prober/LinkProberSw.cpp:45
#10 std::_Construct<link_prober::LinkProberSw, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__p=0x7fdd18022e50) at /usr/include/c++/12/bits/stl_construct.h:119
#11 std::allocator_traits<std::allocator<void> >::construct<link_prober::LinkProberSw, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__p=0x7fdd18022e50) at /usr/include/c++/12/bits/alloc_traits.h:635
#12 std::_Sp_counted_ptr_inplace<link_prober::LinkProberSw, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__a=..., this=0x7fdd18022e40) at /usr/include/c++/12/bits/shared_ptr_base.h:604
#13 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<link_prober::LinkProberSw, std::allocator<void>, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__a=..., __p=<optimized out>, this=<optimized out>) at /usr/include/c++/12/bits/shared_ptr_base.h:971
#14 std::__shared_ptr<link_prober::LinkProberSw, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<void>, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__tag=..., this=<optimized out>, this=<optimized out>, __tag=...) at /usr/include/c++/12/bits/shared_ptr_base.h:1712
#15 std::shared_ptr<link_prober::LinkProberSw>::shared_ptr<std::allocator<void>, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__tag=..., this=<optimized out>, this=<optimized out>, __tag=...) at /usr/include/c++/12/bits/shared_ptr.h:464
#16 std::make_shared<link_prober::LinkProberSw, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> () at /usr/include/c++/12/bits/shared_ptr.h:1010
#17 link_manager::ActiveActiveStateMachine::handleSwssSoCIpv4AddressUpdate (this=0x7fdd20060420, address=...) at src/link_manager/LinkManagerStateMachineActiveActive.cpp:138
#18 0x000055924c0053bb in boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>::operator() (this=0x7fdd270da960, a1=..., p=0x7fdd20060420) at /usr/include/boost/bind/mem_fn_template.hpp:165
#19 boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> >::operator()<boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list0> (a=<synthetic pointer>..., f=..., this=0x7fdd270da970) at /usr/include/boost/bind/bind.hpp:319
#20 boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > >::operator() (this=0x7fdd270da960) at /usr/include/boost/bind/bind.hpp:1294
#21 boost::asio::asio_handler_invoke<boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > > > (function=...) at /usr/include/boost/asio/handler_invoke_hook.hpp:88
#22 boost_asio_handler_invoke_helpers::invoke<boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > >, boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > > > (context=..., function=...) at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:54
#23 boost::asio::detail::handler_work<boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > >, boost::asio::io_context::basic_executor_type<std::allocator<void>, 0u>, void>::complete<boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > > > (handler=..., function=..., this=<synthetic pointer>) at /usr/include/boost/asio/detail/handler_work.hpp:425
#24 boost::asio::detail::completion_handler<boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > >, boost::asio::io_context::basic_executor_type<std::allocator<void>, 0u> >::do_complete (owner=0x55928932d170, base=0x7fdd20049760) at /usr/include/boost/asio/detail/completion_handler.hpp:74
#25 0x000055924bf78be5 in boost::asio::detail::scheduler_operation::complete (bytes_transferred=<optimized out>, ec=..., owner=<optimized out>, this=<optimized out>, this=<optimized out>, owner=<optimized out>, ec=..., bytes_transferred=<optimized out>) at /usr/include/boost/asio/detail/scheduler_operation.hpp:40
#26 boost::asio::detail::strand_service::do_complete (owner=0x55928932d170, base=0x7fdd2005fa80, ec=...) at /usr/include/boost/asio/detail/impl/strand_service.ipp:169
#27 0x000055924c019db6 in boost::asio::detail::scheduler_operation::complete (bytes_transferred=<optimized out>, ec=..., owner=<optimized out>, this=<optimized out>, this=<optimized out>, owner=<optimized out>, ec=..., bytes_transferred=<optimized out>) at /usr/include/boost/asio/detail/scheduler_operation.hpp:40
#28 boost::asio::detail::scheduler::do_run_one (ec=..., this_thread=..., lock=..., this=0x55928932d170) at /usr/include/boost/asio/detail/impl/scheduler.ipp:481
#29 boost::asio::detail::scheduler::run(boost::system::error_code&) [clone .constprop.0] (this=0x55928932d170, ec=...) at /usr/include/boost/asio/detail/impl/scheduler.ipp:204
#30 0x000055924bffe3dc in boost::asio::io_context::run (this=<optimized out>) at /usr/include/boost/asio/impl/io_context.ipp:63
#31 0x00007fdd2aafcb17 in ?? () from /lib/x86_64-linux-gnu/libboost_thread.so.1.74.0
#32 0x00007fdd2a49d1f5 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#33 0x00007fdd2a51cb00 in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7fdd278dc6c0 (LWP 3022) "linkmgrd"):
#0  std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Identity, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [clone .constprop.0] (__k="0xcc4dac36", this=<optimized out>) at /usr/include/c++/12/bits/hashtable.h:1647
#1  0x000055924bf7fd38 in std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::find (__x="0xcc4dac36", this=0x55924c05de20 <link_prober::LinkProberBase::mGuidSet[abi:cxx11]>) at /usr/include/c++/12/bits/unordered_set.h:650
#2  link_prober::LinkProberBase::generateGuid[abi:cxx11]() (this=this@entry=0x7fdd10001ad0) at src/link_prober/LinkProberBase.cpp:715
#3  0x000055924bf80927 in link_prober::LinkProberBase::LinkProberBase (this=<optimized out>, muxPortConfig=..., ioService=..., linkProberStateMachinePtr=<optimized out>, this=<optimized out>, muxPortConfig=..., ioService=..., linkProberStateMachinePtr=<optimized out>) at src/link_prober/LinkProberBase.cpp:66
#4  0x000055924bfc6b28 in link_prober::LinkProberSw::LinkProberSw (linkProberStateMachinePtr=0x7fdd20067c90, ioService=..., muxPortConfig=..., this=0x7fdd10001ad0) at src/link_prober/LinkProberSw.cpp:45
#5  std::_Construct<link_prober::LinkProberSw, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__p=0x7fdd10001ad0) at /usr/include/c++/12/bits/stl_construct.h:119
#6  std::allocator_traits<std::allocator<void> >::construct<link_prober::LinkProberSw, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__p=0x7fdd10001ad0) at /usr/include/c++/12/bits/alloc_traits.h:635
#7  std::_Sp_counted_ptr_inplace<link_prober::LinkProberSw, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__a=..., this=0x7fdd10001ac0) at /usr/include/c++/12/bits/shared_ptr_base.h:604
#8  std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<link_prober::LinkProberSw, std::allocator<void>, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__a=..., __p=<optimized out>, this=<optimized out>) at /usr/include/c++/12/bits/shared_ptr_base.h:971
#9  std::__shared_ptr<link_prober::LinkProberSw, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<void>, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__tag=..., this=<optimized out>, this=<optimized out>, __tag=...) at /usr/include/c++/12/bits/shared_ptr_base.h:1712
#10 std::shared_ptr<link_prober::LinkProberSw>::shared_ptr<std::allocator<void>, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__tag=..., this=<optimized out>, this=<optimized out>, __tag=...) at /usr/include/c++/12/bits/shared_ptr.h:464
#11 std::make_shared<link_prober::LinkProberSw, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> () at /usr/include/c++/12/bits/shared_ptr.h:1010
#12 link_manager::ActiveActiveStateMachine::handleSwssSoCIpv4AddressUpdate (this=0x7fdd20066e20, address=...) at src/link_manager/LinkManagerStateMachineActiveActive.cpp:138
#13 0x000055924c0053bb in boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>::operator() (this=0x7fdd278db960, a1=..., p=0x7fdd20066e20) at /usr/include/boost/bind/mem_fn_template.hpp:165
--Type <RET> for more, q to quit, c to continue without paging--
#14 boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> >::operator()<boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list0> (a=<synthetic pointer>..., f=..., this=0x7fdd278db970) at /usr/include/boost/bind/bind.hpp:319
#15 boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > >::operator() (this=0x7fdd278db960) at /usr/include/boost/bind/bind.hpp:1294
#16 boost::asio::asio_handler_invoke<boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > > > (function=...) at /usr/include/boost/asio/handler_invoke_hook.hpp:88
#17 boost_asio_handler_invoke_helpers::invoke<boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > >, boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > > > (context=..., function=...) at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:54
#18 boost::asio::detail::handler_work<boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > >, boost::asio::io_context::basic_executor_type<std::allocator<void>, 0u>, void>::complete<boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > > > (handler=..., function=..., this=<synthetic pointer>) at /usr/include/boost/asio/detail/handler_work.hpp:425
#19 boost::asio::detail::completion_handler<boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > >, boost::asio::io_context::basic_executor_type<std::allocator<void>, 0u> >::do_complete (owner=0x55928932d170, base=0x7fdd2004b9a0) at /usr/include/boost/asio/detail/completion_handler.hpp:74
#20 0x000055924bf78be5 in boost::asio::detail::scheduler_operation::complete (bytes_transferred=<optimized out>, ec=..., owner=<optimized out>, this=<optimized out>, this=<optimized out>, owner=<optimized out>, ec=..., bytes_transferred=<optimized out>) at /usr/include/boost/asio/detail/scheduler_operation.hpp:40
#21 boost::asio::detail::strand_service::do_complete (owner=0x55928932d170, base=0x7fdd20066480, ec=...) at /usr/include/boost/asio/detail/impl/strand_service.ipp:169
#22 0x000055924c019db6 in boost::asio::detail::scheduler_operation::complete (bytes_transferred=<optimized out>, ec=..., owner=<optimized out>, this=<optimized out>, this=<optimized out>, owner=<optimized out>, ec=..., bytes_transferred=<optimized out>) at /usr/include/boost/asio/detail/scheduler_operation.hpp:40
#23 boost::asio::detail::scheduler::do_run_one (ec=..., this_thread=..., lock=..., this=0x55928932d170) at /usr/include/boost/asio/detail/impl/scheduler.ipp:481
#24 boost::asio::detail::scheduler::run(boost::system::error_code&) [clone .constprop.0] (this=0x55928932d170, ec=...) at /usr/include/boost/asio/detail/impl/scheduler.ipp:204
#25 0x000055924bffe3dc in boost::asio::io_context::run (this=<optimized out>) at /usr/include/boost/asio/impl/io_context.ipp:63
#26 0x00007fdd2aafcb17 in ?? () from /lib/x86_64-linux-gnu/libboost_thread.so.1.74.0
#27 0x00007fdd2a49d1f5 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#28 0x00007fdd2a51cb00 in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7fdd278e31c0 (LWP 3021) "linkmgrd"):
#0  0x00007fdd2a56ed18 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x000055924c0134be in std::char_traits<char>::compare (__n=<optimized out>, __s2=<optimized out>, __s1=<optimized out>) at /usr/include/c++/12/bits/char_traits.h:385
#2  std::operator==<char> (__rhs=..., __lhs="0x300090f3") at /usr/include/c++/12/bits/basic_string.h:3587
#3  std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::operator() (__y=..., __x="0x300090f3", this=<optimized out>) at /usr/include/c++/12/bits/stl_function.h:378
#4  std::__detail::_Hashtable_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__detail::_Identity, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Hashtable_traits<true, true, true> >::_M_key_equals (__n=..., __k="0x300090f3", this=<optimized out>) at /usr/include/c++/12/bits/hashtable_policy.h:1688
#5  std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Identity, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [clone .constprop.0] (__k="0x300090f3", this=<optimized out>) at /usr/include/c++/12/bits/hashtable.h:1648
#6  0x000055924bf7fd38 in std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::find (__x="0x300090f3", this=0x55924c05de20 <link_prober::LinkProberBase::mGuidSet[abi:cxx11]>) at /usr/include/c++/12/bits/unordered_set.h:650
#7  link_prober::LinkProberBase::generateGuid[abi:cxx11]() (this=this@entry=0x559289341f20) at src/link_prober/LinkProberBase.cpp:715
#8  0x000055924bf80927 in link_prober::LinkProberBase::LinkProberBase (this=<optimized out>, muxPortConfig=..., ioService=..., linkProberStateMachinePtr=<optimized out>, this=<optimized out>, muxPortConfig=..., ioService=..., linkProberStateMachinePtr=<optimized out>) at src/link_prober/LinkProberBase.cpp:66
#9  0x000055924bfc6b28 in link_prober::LinkProberSw::LinkProberSw (linkProberStateMachinePtr=0x7fdd20064790, ioService=..., muxPortConfig=..., this=0x559289341f20) at src/link_prober/LinkProberSw.cpp:45
#10 std::_Construct<link_prober::LinkProberSw, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__p=0x559289341f20) at /usr/include/c++/12/bits/stl_construct.h:119
#11 std::allocator_traits<std::allocator<void> >::construct<link_prober::LinkProberSw, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__p=0x559289341f20) at /usr/include/c++/12/bits/alloc_traits.h:635
#12 std::_Sp_counted_ptr_inplace<link_prober::LinkProberSw, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__a=..., this=0x559289341f10) at /usr/include/c++/12/bits/shared_ptr_base.h:604
#13 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<link_prober::LinkProberSw, std::allocator<void>, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__a=..., __p=<optimized out>, this=<optimized out>) at /usr/include/c++/12/bits/shared_ptr_base.h:971
#14 std::__shared_ptr<link_prober::LinkProberSw, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<void>, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__tag=..., this=<optimized out>, this=<optimized out>, __tag=...) at /usr/include/c++/12/bits/shared_ptr_base.h:1712
#15 std::shared_ptr<link_prober::LinkProberSw>::shared_ptr<std::allocator<void>, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> (__tag=..., this=<optimized out>, this=<optimized out>, __tag=...) at /usr/include/c++/12/bits/shared_ptr.h:464
#16 std::make_shared<link_prober::LinkProberSw, common::MuxPortConfig&, boost::asio::io_context&, link_prober::LinkProberStateMachineBase*> () at /usr/include/c++/12/bits/shared_ptr.h:1010
#17 link_manager::ActiveActiveStateMachine::handleSwssSoCIpv4AddressUpdate (this=0x7fdd20063920, address=...) at src/link_manager/LinkManagerStateMachineActiveActive.cpp:138
#18 0x000055924c0053bb in boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>::operator() (this=0x7ffc7a022a60, a1=..., p=0x7fdd20063920) at /usr/include/boost/bind/mem_fn_template.hpp:165
#19 boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> >::operator()<boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list0> (a=<synthetic pointer>..., f=..., this=0x7ffc7a022a70) at /usr/include/boost/bind/bind.hpp:319
#20 boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > >::operator() (this=0x7ffc7a022a60) at /usr/include/boost/bind/bind.hpp:1294
#21 boost::asio::asio_handler_invoke<boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > > > (function=...) at /usr/include/boost/asio/handler_invoke_hook.hpp:88
#22 boost_asio_handler_invoke_helpers::invoke<boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > >, boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > > > (context=..., function=...) at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:54
#23 boost::asio::detail::handler_work<boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > >, boost::asio::io_context::basic_executor_type<std::allocator<void>, 0u>, void>::complete<boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > > > (handler=..., function=..., this=<synthetic pointer>) at /usr/include/boost/asio/detail/handler_work.hpp:425
#24 boost::asio::detail::completion_handler<boost::_bi::bind_t<void, boost::_mfi::mf1<void, link_manager::LinkManagerStateMachineBase, boost::asio::ip::address>, boost::_bi::list2<boost::_bi::value<link_manager::LinkManagerStateMachineBase*>, boost::_bi::value<boost::asio::ip::address> > >, boost::asio::io_context::basic_executor_type<std::allocator<void>, 0u> >::do_complete (owner=0x55928932d170, base=0x7fdd20049bb0) at /usr/include/boost/asio/detail/completion_handler.hpp:74
#25 0x000055924bf78be5 in boost::asio::detail::scheduler_operation::complete (bytes_transferred=<optimized out>, ec=..., owner=<optimized out>, this=<optimized out>, this=<optimized out>, owner=<optimized out>, ec=..., bytes_transferred=<optimized out>) at /usr/include/boost/asio/detail/scheduler_operation.hpp:40
#26 boost::asio::detail::strand_service::do_complete (owner=0x55928932d170, base=0x7fdd20062f80, ec=...) at /usr/include/boost/asio/detail/impl/strand_service.ipp:169
#27 0x000055924c019db6 in boost::asio::detail::scheduler_operation::complete (bytes_transferred=<optimized out>, ec=..., owner=<optimized out>, this=<optimized out>, this=<optimized out>, owner=<optimized out>, ec=..., bytes_transferred=<optimized out>) at /usr/include/boost/asio/detail/scheduler_operation.hpp:40
#28 boost::asio::detail::scheduler::do_run_one (ec=..., this_thread=..., lock=..., this=0x55928932d170) at /usr/include/boost/asio/detail/impl/scheduler.ipp:481
#29 boost::asio::detail::scheduler::run(boost::system::error_code&) [clone .constprop.0] (this=0x55928932d170, ec=...) at /usr/include/boost/asio/detail/impl/scheduler.ipp:204
#30 0x000055924bffe3dc in boost::asio::io_context::run (this=<optimized out>) at /usr/include/boost/asio/impl/io_context.ipp:63
#31 0x000055924bf60c27 in mux::MuxManager::run (this=0x55928932cdf0) at src/MuxManager.cpp:141
#32 main (argc=<optimized out>, argv=<optimized out>) at src/LinkMgrdMain.cpp:140
```

### PR DESCRIPTION
**Pull request by lolyu**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Doc/Design
- [ ] Unit test

#### What is the motivation for this PR?
Fix #307 

The mux port health is `uninitialized` in nightly.
And from the syslog, the state machines are not activated as the link probers are trying to generate `GUID`. The `GUID` generation logic is stuck somehow in the multi-threading environment.
From the backtrace on each threads, some threads is busy looping the generated `GUID` set while some threads are trying to insert new `GUID` into the set; this is a race condition as the C++ multiset is not thread-safe.

Signed-off-by: Longxiang Lyu <lolv@microsoft.com>

##### Work item tracking
- Microsoft ADO **(number only)**: 34335369

#### How did you do it?
Let's wrap the generated `GUID` set update/read code section with a lock.

#### How did you verify/test it?
1. UT.
2. use the script in the issue, run over 12h, no repro.

### CODE REVIEW

**Comment by lolyu** [comment]
Hi @harjotsinghpawra, please help review.

File: src/link_prober/LinkProberBase.cpp [hunk 1]
```diff
@@ -712,6 +713,7 @@ std::string LinkProberBase::generateGuid()
     std::fill(generatedGuid.begin(), generatedGuid.end() - 4, 0);
     auto generatedGuidStr = uuidToHexString(generatedGuid);
     generatedGuidStr = "0x" + generatedGuidStr.substr(generatedGuidStr.length() - 8);
+    std::lock_guard<std::recursive_mutex> lock(mGuidSetMtx);
```
Comment (manamand2020) [inline src/link_prober/LinkProberBase.cpp:716]: There are other places where we insert/delete from this set for peer guid from LinkProberSw and LinkProberHw. It would be better to add the lock_guard even there.

Comment (manamand2020) [reply src/link_prober/LinkProberBase.cpp:716]: With hardware offload we need unique GUIDs, so we will need those. @harjotsinghpawra can you work on fixing this properly?

Comment (lolyu) [reply src/link_prober/LinkProberBase.cpp:716]: Discussed with @manamand2020, the insert/delete from `mGuidSet` will be fixed by future PR from Cisco, this PR is only fixing the race conditon during state machine init phase.

**Comment by lolyu** [comment]
Hi @zjswhhh, please help review
