### PR TITLE
Fix mux config when gRPC connection is lost

### LINKED ISSUE #165: `linkmgrd` fails to change back to `active` when gRPC connection is lost
How to reproduce:
1. verify `Ethernet4` is in `active` state initially, and disable the gRPC server on NiC.
```
# show mux s | grep -w Ethernet4
Ethernet4   active    active           healthy   consistent  2023-Feb-08 12:50:21.305147
```
2. config mux mode to `standby`
```
# config mux mode standby Ethernet4
port       state
---------  ----------
Ethernet4  INPROGRESS
# show mux s | grep -w Ethernet4
Ethernet4   standby   unknown          healthy   inconsistent
```
3. config mux mode back to `auto`
```
# config mux mode auto Ethernet4
port       state
---------  -------
Ethernet4  OK
```
4. the status is still `standby` locally, and the tunnel routes are not removed
```
# show mux s | grep -w Ethernet4
Ethernet4   standby   unknown          healthy   inconsistent
# show mux tun
PORT        DEST_TYPE    DEST_ADDRESS       kernel    asic
----------  -----------  -----------------  --------  ------
Ethernet4   server_ipv4  192.168.0.2/32     added     added
Ethernet4   server_ipv6  fc02:1000::2/128   added     added
Ethernet4   soc_ipv4     192.168.0.3/32     -         added
```

### PR DESCRIPTION
**Pull request by lolyu**
### Description of PR

Summary:
Fixes #165

### Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Doc/Design
- [ ] Unit test

#### What is the motivation for this PR?
Fix issue: https://github.com/sonic-net/sonic-linkmgrd/issues/165

Signed-off-by: Longxiang Lyu <lolv@microsoft.com>

#### How did you do it?
Reset the link prober state if the mux state is unknown when the mux config is changed back from `active` or `standby` to `auto`.

### CODE REVIEW

File: src/link_manager/LinkManagerStateMachineActiveActive.cpp [hunk 1]
```diff
@@ -241,6 +241,8 @@ void ActiveActiveStateMachine::handleMuxConfigNotification(const common::MuxPort
         CompositeState nextState = mCompositeState;
         if (mode == common::MuxPortConfig::Mode::Active && ms(mCompositeState) != mux_state::MuxState::Label::Active) {
             switchMuxState(nextState, mux_state::MuxState::Label::Active, true);
+        } else if (mode == common::MuxPortConfig::Mode::Auto && ms(mCompositeState) == mux_state::MuxState::Label::Unknown) {
+            initLinkProberState(nextState);
```
Comment (zjswhhh) [inline src/link_manager/LinkManagerStateMachineActiveActive.cpp:245]: Can we add some comments here?

**Review by zjswhhh — APPROVED** [review]
